import { LessonNote, ExamPaper } from '../types';
import { DEFAULT_CREST_DATA_URL } from './schoolLogo';

export const SAMPLE_PRESETS = [
  {
    id: 'nursery-body',
    academicLevel: 'nursery' as const,
    subLevel: 'KG 2',
    subject: 'Health Habits & Literacy',
    topic: 'My Wonderful Body & Washing Hands',
    duration: '30 mins',
    numberOfPeriods: 2,
    content: `Parts of the body: head, eyes, ears, nose, mouth, hands, and feet.
Why we wash our hands with soap and water: to chase away tiny germs we cannot see.
When to wash hands: before eating food, after playing outside in the sand, and after using the toilet.
Song/Rhyme: "Wash, wash, wash your hands, make them nice and clean! Rub the top and rub the palms, cleanest ever seen!"`,
  },
  {
    id: 'primary-water-cycle',
    academicLevel: 'primary' as const,
    subLevel: 'Basic 4',
    subject: 'Basic Science & Technology',
    topic: 'The Water Cycle and States of Matter',
    duration: '45 mins',
    numberOfPeriods: 3,
    content: `Three states of water: Solid (ice), Liquid (drinking water), and Gas (water vapor / steam).
The 4 stages of the water cycle:
1. Evaporation: The sun heats up water from rivers, lakes, and oceans. The water turns into invisible vapor and rises into the sky.
2. Condensation: High up in the cool sky, water vapor cools down and joins together to form fluffy clouds.
3. Precipitation: When clouds get too heavy with water droplets, they fall back to earth as rain, snow, or sleet.
4. Collection: Rainwater collects into rivers, streams, and oceans, and the cycle begins all over again.
Key facts: Water never disappears; it is recycled again and again on Earth!`,
  },
  {
    id: 'secondary-photosynthesis',
    academicLevel: 'secondary' as const,
    subLevel: 'JSS 2',
    subject: 'Biology / Integrated Science',
    topic: 'Photosynthesis & Plant Nutrition',
    duration: '60 mins',
    numberOfPeriods: 4,
    content: `Definition: Photosynthesis is the biochemical process by which green plants manufacture their own food (glucose) using sunlight, water, and carbon dioxide in the presence of chlorophyll.
Chemical Equation: 6CO2 + 6H2O + Sunlight -> C6H12O6 + 6O2
Raw materials needed:
- Carbon dioxide (absorbed through stomata on leaves)
- Water (absorbed from soil via root hair cells and transported via xylem)
- Sunlight (absorbed by the green pigment chlorophyll inside chloroplasts)
Products:
- Glucose (used for plant energy, growth, or stored as starch)
- Oxygen (by-product released into atmosphere for respiration of living organisms)
Significance: Primary source of food on Earth, sustains atmospheric oxygen balance, reduces greenhouse gases.`,
  },
];

export const INITIAL_LESSON_NOTE: LessonNote = {
  id: 'sample-primary-water',
  createdAt: new Date().toISOString(),
  subject: 'Basic Science',
  topic: 'The Water Cycle: Earth’s Natural Recycler',
  academicLevel: 'primary',
  subLevel: 'Basic 4',
  duration: '45 mins',
  numberOfPeriods: 3,
  periodAllocationSummary: '3 Teaching Periods (45 mins each)',
  targetAgeGroup: '9 - 10 years',
  overview: 'In this 3-period lesson unit, pupils explore how water moves continuously between the Earth and the sky through three structured instructional sessions covering states of matter, the 4-stage cycle, and hands-on demonstrations.',
  learningObjectives: [
    'Identify the three forms of water: solid (ice), liquid (water), and gas (steam/vapor).',
    'Describe the four main stages of the water cycle in simple words.',
    'Explain why rain falls from clouds when they become heavy.',
    'Demonstrate how the water cycle works using a simple zip-lock bag classroom model.',
  ],
  keyVocabulary: [
    {
      term: 'Water Cycle',
      simpleDefinition: 'The endless journey water takes from the ground to the clouds and back down to the ground.',
      exampleSentence: 'Rain is an important part of the water cycle.',
    },
    {
      term: 'Evaporation',
      simpleDefinition: 'When liquid water warms up from the sun and turns into an invisible gas called water vapor.',
      exampleSentence: 'A puddle on the road dries up because of evaporation.',
    },
    {
      term: 'Condensation',
      simpleDefinition: 'When invisible water vapor cools down and turns into tiny water droplets to form clouds.',
      exampleSentence: 'You see condensation on a cold glass of lemonade.',
    },
    {
      term: 'Precipitation',
      simpleDefinition: 'Water falling from clouds down to Earth as rain, drizzle, or hail.',
      exampleSentence: 'We use umbrellas during heavy precipitation.',
    },
    {
      term: 'Collection',
      simpleDefinition: 'Water gathering together in rivers, lakes, ponds, and oceans.',
      exampleSentence: 'Streams flow downhill for collection in the sea.',
    },
  ],
  sections: [
    {
      periodNumber: 1,
      periodTitle: 'Period 1: The Three Physical States of Water',
      title: 'What Are the Three States of Water?',
      subTopics: ['Matter and physical states', 'Solid ice cubes', 'Liquid drinking water', 'Water vapor & steam'],
      explanationBulletPoints: [
        'Water is special because it can exist in three different shapes or states.',
        'Solid state: Ice cubes in the freezer are hard and hold their shape.',
        'Liquid state: The water we drink, wash with, and swim in.',
        'Gas state: Water vapor that rises from a hot bowl of soup or boiling kettle.',
      ],
      everydayAnalogyOrExample: 'Think of water as a shapeshifter: cold makes it freeze like a stone, warm makes it run like a river, and heat makes it fly like air!',
      teacherTipOrBoardPrompt: 'Draw three simple boxes on the board: Ice cube, Water cup, and Cloud steam.',
    },
    {
      periodNumber: 2,
      periodTitle: 'Period 2: The 4 Big Steps of the Water Cycle',
      title: 'The 4 Big Steps of the Water Cycle',
      subTopics: ['Evaporation from solar heat', 'Condensation into clouds', 'Precipitation rain clouds', 'Collection in streams'],
      explanationBulletPoints: [
        'Step 1 (Evaporation): The hot sun shines on puddles, rivers, and seas. The water gets warm and floats up into the sky as light vapor.',
        'Step 2 (Condensation): As the water vapor climbs higher into the chilly sky, it shivers, cools down, and hugs other droplets to create fluffy white or grey clouds.',
        'Step 3 (Precipitation): The cloud gets fuller and darker until it cannot hold the heavy water anymore. Splash! It drops down as rain.',
        'Step 4 (Collection): The fallen rain flows into soil, drains, streams, and oceans. Then the sun shines again, and the magic cycle restarts!',
      ],
      everydayAnalogyOrExample: 'It is just like a giant water wheel or carousel that never stops turning on planet Earth.',
      teacherTipOrBoardPrompt: 'Have students repeat with hand motions: Hands up (Evaporation), Hands together (Condensation), Wiggle fingers down (Precipitation), Hands sweep wide (Collection).',
    },
    {
      periodNumber: 3,
      periodTitle: 'Period 3: Ecological Importance & Hands-on Demonstration',
      title: 'Why is the Water Cycle Important to Us?',
      subTopics: ['Nature recycling clean water', 'Supporting agriculture & crops', 'Conserving fresh water resources'],
      explanationBulletPoints: [
        'It gives clean fresh water to plants, trees, farm crops, and drinking reservoirs.',
        'It cleans our air and keeps weather temperatures balanced.',
        'The water dinosaur drank millions of years ago is the exact same water we drink today!',
      ],
      everydayAnalogyOrExample: 'Earth does not make brand new water; it is the ultimate nature recycler.',
      teacherTipOrBoardPrompt: 'Board Prompt: Ask 3 pupils to identify where water goes after it rains on the school field.',
    },
  ],
  classActivities: [
    {
      title: 'The Mini Water Cycle in a Zip-Lock Bag',
      durationMinutes: '15 mins',
      activityType: 'Pair Work / Demonstration',
      materialsNeeded: [
        'Clear zip-lock sandwich bags (1 per pair)',
        'Blue food coloring (optional)',
        'Water (approx. 2 tablespoons per bag)',
        'Permanent markers',
        'Tape to stick bags onto a sunny classroom window',
      ],
      stepByStepInstructions: [
        'Step 1: Students use markers to draw the sun, a cloud, and ocean waves on the plastic bag.',
        'Step 2: Pour 2 tablespoons of water (tinted blue) into the bottom of the bag.',
        'Step 3: Seal the zip-lock securely to trap the air and water inside.',
        'Step 4: Tape the bag to a bright, sunny window.',
        'Step 5: Observe how the sun warms the water (evaporation), droplets form on the bag walls (condensation), and slide back down (precipitation)!',
      ],
      expectedOutcome: 'Pupils visibly witness all four stages of the water cycle happening in real-time inside their transparent bag.',
    },
  ],
  homework: {
    title: 'Water Detective & Cloud Observation Sheet',
    instructions: 'Complete the three short tasks below in your science notebook. Ask an older family member to help you spot examples!',
    questionsOrTasks: [
      'Question 1: Name the three states of water and draw one example of each in your notebook.',
      'Question 2: Look outside your window before dinner. Describe the clouds in the sky. Are they white and fluffy or dark and heavy?',
      'Question 3: Kitchen experiment: When someone boils water in a pot with a lid, what appears under the lid when you lift it? Which step of the water cycle is this?',
      'Question 4 (Bonus): Write down two reasons why we must turn off running taps while brushing our teeth.',
    ],
    guidanceForParentsOrSelfStudy: 'Parents: Please supervise children near warm cooking appliances. Encourage your child to describe what happens in their own words.',
    submissionDeadlineNote: 'Due next Science period (Thursday morning).',
  },
  quickSummaryChecklist: [
    'Water exists as Ice (solid), Water (liquid), and Vapor (gas).',
    'Evaporation is water rising into the sky as vapor.',
    'Condensation is water vapor forming clouds.',
    'Precipitation is rain falling back down.',
    'Collection is water gathering in lakes and seas.',
  ],
  teacherPedagogyNotes: 'At the Primary level, focus on visual kinesthetics. Repeating the four-stage hand gesture song ensures 100% retention before the end of the 45-minute period.',
};

export const INITIAL_EXAM_PAPER: ExamPaper = {
  id: 'sample-primary-water-exam',
  createdAt: new Date().toISOString(),
  schoolName: 'BEACON HILL SCHOOLS',
  schoolLogoUrl: DEFAULT_CREST_DATA_URL,
  termOrSemester: 'First Term Examination',
  academicSession: '2025/2026 Academic Session',
  examTitle: 'FIRST TERM CONTINUOUS ASSESSMENT & EXAMINATION',
  subject: 'Basic Science & Technology',
  topic: 'Comprehensive Term Examination (The Water Cycle, States of Matter, Heat Energy & Environment)',
  coveredTopics: [
    'The Water Cycle & Its Stages',
    'Three States of Matter (Solid, Liquid, Gas)',
    'Evaporation, Condensation & Precipitation',
    'Heat Energy and Melting / Freezing',
    'Water Conservation & Environmental Hygiene',
  ],
  academicLevel: 'primary',
  subLevel: 'Basic 4',
  timeAllowed: '1 Hour 30 Minutes',
  totalMarks: 100,
  difficulty: 'standard',
  generalInstructions: [
    'Section A: 30 Multiple Choice Questions (1 Mark each = 30 Marks). Write your choice clearly.',
    'Section B: 8 Theory Questions (Answer all questions = 70 Marks). Write neatly in the spaces provided.',
    'Maximum time allowed is 1 hour 30 minutes. Strict examination ethics apply.',
  ],
  sections: [
    {
      sectionCode: 'SECTION A',
      sectionTitle: 'OBJECTIVE QUESTIONS (30 MARKS)',
      instructions: 'Choose the correct option from the alternatives lettered A to D.',
      totalMarksForSection: 30,
      questions: [
        {
          questionNumber: 1,
          questionText: 'What provides the natural heat energy that powers evaporation in oceans and lakes?',
          options: ['A) The cold moon', 'B) The hot sun', 'C) Wind currents', 'D) Rain clouds'],
          marks: 1,
          correctAnswer: 'B) The hot sun',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 2,
          questionText: 'When liquid water freezes at zero degrees Celsius, it changes into which state?',
          options: ['A) Solid ice', 'B) Clear liquid', 'C) Invisible gas', 'D) Warm steam'],
          marks: 1,
          correctAnswer: 'A) Solid ice',
          markingSchemeOrRubric: 'Award 1 mark for option A.',
        },
        {
          questionNumber: 3,
          questionText: 'Which scientific term describes water falling from the sky as rain or snow?',
          options: ['A) Evaporation', 'B) Condensation', 'C) Precipitation', 'D) Filtration'],
          marks: 1,
          correctAnswer: 'C) Precipitation',
          markingSchemeOrRubric: 'Award 1 mark for option C.',
        },
        {
          questionNumber: 4,
          questionText: 'Clouds in the sky are formed during which stage of the water cycle?',
          options: ['A) Evaporation', 'B) Condensation', 'C) Melting', 'D) Freezing'],
          marks: 1,
          correctAnswer: 'B) Condensation',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 5,
          questionText: 'Why is the water movement on Earth called a "cycle"?',
          options: [
            'A) It only happens once a year',
            'B) It stops completely in rainy season',
            'C) It repeats continuously in an endless journey',
            'D) It is shaped like a bicycle wheel',
          ],
          marks: 1,
          correctAnswer: 'C) It repeats continuously in an endless journey',
          markingSchemeOrRubric: 'Award 1 mark for option C.',
        },
        {
          questionNumber: 6,
          questionText: 'Water vapor is best described as which state of matter?',
          options: ['A) Solid', 'B) Liquid', 'C) Gas', 'D) Plasma'],
          marks: 1,
          correctAnswer: 'C) Gas',
          markingSchemeOrRubric: 'Award 1 mark for option C.',
        },
        {
          questionNumber: 7,
          questionText: 'Which of the following is a direct example of condensation in everyday life?',
          options: [
            'A) Water boiling in a kettle',
            'B) Morning dew on green grass leaves',
            'C) Wet laundry drying in the breeze',
            'D) Ice cube melting on a plate',
          ],
          marks: 1,
          correctAnswer: 'B) Morning dew on green grass leaves',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 8,
          questionText: 'Which process changes a solid ice block directly into liquid water?',
          options: ['A) Melting', 'B) Freezing', 'C) Boiling', 'D) Condensing'],
          marks: 1,
          correctAnswer: 'A) Melting',
          markingSchemeOrRubric: 'Award 1 mark for option A.',
        },
        {
          questionNumber: 9,
          questionText: 'Where does most of Earth’s evaporated water originate from?',
          options: ['A) Swimming pools', 'B) Oceans and seas', 'C) Rainwater tanks', 'D) Household sinks'],
          marks: 1,
          correctAnswer: 'B) Oceans and seas',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 10,
          questionText: 'When water is heated to 100°C, it reaches its:',
          options: ['A) Freezing point', 'B) Boiling point', 'C) Melting point', 'D) Resting point'],
          marks: 1,
          correctAnswer: 'B) Boiling point',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 11,
          questionText: 'Plants release water vapor into the air through their leaves in a process called:',
          options: ['A) Transpiration', 'B) Respiration', 'C) Digestion', 'D) Germination'],
          marks: 1,
          correctAnswer: 'A) Transpiration',
          markingSchemeOrRubric: 'Award 1 mark for option A.',
        },
        {
          questionNumber: 12,
          questionText: 'Which state of matter has a fixed volume but takes the shape of its container?',
          options: ['A) Solid', 'B) Liquid', 'C) Gas', 'D) Vapor'],
          marks: 1,
          correctAnswer: 'B) Liquid',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 13,
          questionText: 'Which instrument is used to measure rainfall in millimeters?',
          options: ['A) Thermometer', 'B) Rain gauge', 'C) Barometer', 'D) Wind vane'],
          marks: 1,
          correctAnswer: 'B) Rain gauge',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 14,
          questionText: 'Water stored naturally underground inside rocks is known as:',
          options: ['A) Surface water', 'B) Groundwater', 'C) Saltwater', 'D) River water'],
          marks: 1,
          correctAnswer: 'B) Groundwater',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 15,
          questionText: 'What happens to the molecules of water when it is heated?',
          options: [
            'A) They stop moving completely',
            'B) They move faster and spread apart',
            'C) They get heavier and freeze',
            'D) They turn into stone',
          ],
          marks: 1,
          correctAnswer: 'B) They move faster and spread apart',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 16,
          questionText: 'Which of the following is NOT one of the three common states of matter?',
          options: ['A) Solid', 'B) Liquid', 'C) Mineral', 'D) Gas'],
          marks: 1,
          correctAnswer: 'C) Mineral',
          markingSchemeOrRubric: 'Award 1 mark for option C.',
        },
        {
          questionNumber: 17,
          questionText: 'Why do wet clothes dry faster on a windy, sunny afternoon?',
          options: [
            'A) Evaporation occurs more rapidly',
            'B) Precipitation cools the fabric',
            'C) Condensation traps water inside',
            'D) The wind freezes the droplets',
          ],
          marks: 1,
          correctAnswer: 'A) Evaporation occurs more rapidly',
          markingSchemeOrRubric: 'Award 1 mark for option A.',
        },
        {
          questionNumber: 18,
          questionText: 'Which of the following is safe for direct human drinking?',
          options: ['A) Untreated ocean water', 'B) Stagnant puddle water', 'C) Filtered and boiled water', 'D) Gutter runoff'],
          marks: 1,
          correctAnswer: 'C) Filtered and boiled water',
          markingSchemeOrRubric: 'Award 1 mark for option C.',
        },
        {
          questionNumber: 19,
          questionText: 'Droplets collecting on the outside of an icy beverage glass come from:',
          options: [
            'A) Water leaking through the glass',
            'B) Moisture in the surrounding warm air',
            'C) Melting ice inside the glass',
            'D) Fingerprints on the rim',
          ],
          marks: 1,
          correctAnswer: 'B) Moisture in the surrounding warm air',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 20,
          questionText: 'The stage where rainwater gathers into streams, rivers, and oceans is:',
          options: ['A) Collection', 'B) Evaporation', 'C) Sublimation', 'D) Boiling'],
          marks: 1,
          correctAnswer: 'A) Collection',
          markingSchemeOrRubric: 'Award 1 mark for option A.',
        },
        {
          questionNumber: 21,
          questionText: 'Solid matter is characterized by having:',
          options: [
            'A) No definite shape or volume',
            'B) Definite shape and definite volume',
            'C) Definite shape but changing volume',
            'D) Invisible floating particles',
          ],
          marks: 1,
          correctAnswer: 'B) Definite shape and definite volume',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 22,
          questionText: 'Which of the following actions best helps conserve fresh water at home?',
          options: [
            'A) Leaving the tap running while brushing teeth',
            'B) Fixing leaking pipes and dripping taps promptly',
            'C) Washing one cup with a full bucket of water',
            'D) Pouring clean water onto the street',
          ],
          marks: 1,
          correctAnswer: 'B) Fixing leaking pipes and dripping taps promptly',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 23,
          questionText: 'What happens when water vapor rises high up into the cooler upper atmosphere?',
          options: [
            'A) It burns into flames',
            'B) It condenses to form cloud droplets',
            'C) It disappears into outer space forever',
            'D) It turns into solid rock',
          ],
          marks: 1,
          correctAnswer: 'B) It condenses to form cloud droplets',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 24,
          questionText: 'Hailstones and sleet are examples of which stage of the water cycle?',
          options: ['A) Evaporation', 'B) Precipitation', 'C) Condensation', 'D) Collection'],
          marks: 1,
          correctAnswer: 'B) Precipitation',
          markingSchemeOrRubric: 'Award 1 mark for option B.',
        },
        {
          questionNumber: 25,
          questionText: 'What state of matter is the helium gas inside a floating party balloon?',
          options: ['A) Solid', 'B) Liquid', 'C) Gas', 'D) Gel'],
          marks: 1,
          correctAnswer: 'C) Gas',
          markingSchemeOrRubric: 'Award 1 mark for option C.',
        },
        {
          questionNumber: 26,
          questionText: 'Which change of state occurs when a hot iron causes damp clothing to steam?',
          options: ['A) Liquid to gas', 'B) Gas to liquid', 'C) Solid to liquid', 'D) Gas to solid'],
          marks: 1,
          correctAnswer: 'A) Liquid to gas',
          markingSchemeOrRubric: 'Award 1 mark for option A.',
        },
        {
          questionNumber: 27,
          questionText: 'Why can fish and aquatic creatures survive underwater?',
          options: [
            'A) Water contains dissolved oxygen',
            'B) Fish do not need any air',
            'C) Fish breathe only water vapor',
            'D) Water is a solid structure',
          ],
          marks: 1,
          correctAnswer: 'A) Water contains dissolved oxygen',
          markingSchemeOrRubric: 'Award 1 mark for option A.',
        },
        {
          questionNumber: 28,
          questionText: 'Which property describes a gas spreading out to fill any room or container?',
          options: ['A) Compressibility and diffusion', 'B) Hardness', 'C) Freezing', 'D) Stiffness'],
          marks: 1,
          correctAnswer: 'A) Compressibility and diffusion',
          markingSchemeOrRubric: 'Award 1 mark for option A.',
        },
        {
          questionNumber: 29,
          questionText: 'When a pot lid is lifted over simmering soup, water droplets roll down. Why?',
          options: [
            'A) Rising steam cooled against the underside of the lid',
            'B) The lid absorbed water from the air',
            'C) The cook splashed water on the lid',
            'D) The pot melted slightly',
          ],
          marks: 1,
          correctAnswer: 'A) Rising steam cooled against the underside of the lid',
          markingSchemeOrRubric: 'Award 1 mark for option A.',
        },
        {
          questionNumber: 30,
          questionText: 'What role do trees and forests play in the regional water cycle?',
          options: [
            'A) They absorb and release moisture to encourage rainfall',
            'B) They dry out the atmosphere completely',
            'C) They stop clouds from moving',
            'D) They turn precipitation into dust',
          ],
          marks: 1,
          correctAnswer: 'A) They absorb and release moisture to encourage rainfall',
          markingSchemeOrRubric: 'Award 1 mark for option A.',
        },
      ],
    },
    {
      sectionCode: 'SECTION B',
      sectionTitle: 'THEORY QUESTIONS (70 MARKS)',
      instructions: 'Answer all eight (8) questions in this section clearly in the spaces provided.',
      totalMarksForSection: 70,
      questions: [
        {
          questionNumber: 1,
          questionText: '(a) Define the term "Water Cycle". (b) List the FOUR major stages of the water cycle in the order they occur. (c) Explain the vital role played by the Sun in this cycle.',
          marks: 10,
          correctAnswer: '(a) The water cycle is the continuous journey of water evaporating from Earth into the atmosphere, condensing into clouds, and falling back as precipitation. (b) 1. Evaporation, 2. Condensation, 3. Precipitation, 4. Collection. (c) The Sun provides heat energy that warms oceans, lakes, and rivers, converting liquid water into water vapor.',
          markingSchemeOrRubric: 'Part (a): 3 marks for complete definition; Part (b): 4 marks (1 mark per stage in sequence); Part (c): 3 marks for mentioning solar heat driving evaporation.',
        },
        {
          questionNumber: 2,
          questionText: '(a) State the THREE states of matter in which water can exist. (b) Give TWO everyday examples of water in each state. (c) What temperature in Celsius represents the boiling point of pure water?',
          marks: 8,
          correctAnswer: '(a) Solid, Liquid, and Gas. (b) Solid: Ice cubes, hail, glaciers; Liquid: Tap water, rain, rivers; Gas: Steam from a kettle, water vapor, fog. (c) 100°C.',
          markingSchemeOrRubric: 'Part (a): 3 marks (1 mark each); Part (b): 3 marks (0.5 mark per valid example); Part (c): 2 marks for 100°C.',
        },
        {
          questionNumber: 3,
          questionText: '(a) Differentiate clearly between "Evaporation" and "Condensation". (b) Describe a simple classroom or kitchen observation demonstrating condensation.',
          marks: 8,
          correctAnswer: '(a) Evaporation is the change of liquid water into gas/vapor due to heat; Condensation is the change of gas/vapor back into liquid water due to cooling. (b) Cold glass observation: Pouring ice water into a dry glass results in water droplets forming on the outer wall as warm air cools upon contact.',
          markingSchemeOrRubric: 'Part (a): 4 marks (2 marks for each process definition); Part (b): 4 marks for clear, accurate observation description.',
        },
        {
          questionNumber: 4,
          questionText: '(a) What is "Precipitation"? (b) Mention THREE different forms precipitation can take when falling to the ground. (c) Why is precipitation crucial for agriculture and farming?',
          marks: 8,
          correctAnswer: '(a) Precipitation is any form of water that falls from clouds in the atmosphere to Earth’s surface. (b) Rain, snow, sleet, hail. (c) It irrigates crops, replenishes soil moisture, and refills farm reservoirs.',
          markingSchemeOrRubric: 'Part (a): 2 marks; Part (b): 3 marks (1 mark per form); Part (c): 3 marks for agronomic importance.',
        },
        {
          questionNumber: 5,
          questionText: '(a) Explain what happens to water molecules when liquid water is placed in a freezer at -5°C. (b) What is this change of state called? (c) Why does an ice cube float on top of liquid water?',
          marks: 8,
          correctAnswer: '(a) Molecules lose heat energy, slow down, and lock into a rigid crystal structure. (b) Freezing (or solidification). (c) Ice is less dense than liquid water because water molecules expand slightly as they freeze.',
          markingSchemeOrRubric: 'Part (a): 3 marks; Part (b): 2 marks; Part (c): 3 marks for identifying density difference.',
        },
        {
          questionNumber: 6,
          questionText: '(a) What is "Transpiration"? (b) How do plant roots and leaves participate in returning water to the sky? (c) What would happen to regional rainfall if all the trees in a community were cut down (deforestation)?',
          marks: 9,
          correctAnswer: '(a) Transpiration is the biological process where plants absorb water through roots and release it as invisible vapor through tiny pores (stomata) on leaves. (b) Roots absorb groundwater; stems transport it up; leaves evaporate it. (c) Deforestation reduces atmospheric humidity, leading to decreased rainfall, droughts, and soil erosion.',
          markingSchemeOrRubric: 'Part (a): 3 marks; Part (b): 3 marks; Part (c): 3 marks for explaining reduced rainfall and drought risk.',
        },
        {
          questionNumber: 7,
          questionText: '(a) Identify TWO major sources of water pollution in our communities. (b) State TWO dangers of drinking polluted water. (c) Describe TWO simple methods a family can use to make contaminated water safe for drinking.',
          marks: 9,
          correctAnswer: '(a) Chemical waste from factories, untreated sewage, oil spills, and dumping plastic refuse in streams. (b) Diseases like cholera, typhoid, dysentery; poisoning from chemicals. (c) 1. Boiling water vigorously for 5–10 minutes; 2. Filtration followed by chemical water purification tablets (chlorination).',
          markingSchemeOrRubric: 'Part (a): 3 marks (1.5 marks per source); Part (b): 3 marks (1.5 marks per hazard); Part (c): 3 marks (1.5 marks per valid treatment method).',
        },
        {
          questionNumber: 8,
          questionText: '(a) Why is fresh drinking water considered a scarce and precious resource, even though water covers over 70% of Earth’s surface? (b) List THREE practical habits primary pupils should adopt at school and home to prevent water wastage.',
          marks: 10,
          correctAnswer: '(a) Over 97% of Earth’s water is salty ocean water unfit for drinking or agriculture, and over 2% is locked in polar ice caps, leaving less than 1% as accessible freshwater. (b) 1. Turning off taps securely while soaping hands or brushing teeth; 2. Reporting leaky school taps immediately to teachers; 3. Reusing clean rinse water for watering school garden plants.',
          markingSchemeOrRubric: 'Part (a): 4 marks for explaining that most water is saline and only <1% is accessible fresh water; Part (b): 6 marks (2 marks per practical conservation habit).',
        },
      ],
    },
  ],
  teacherGradingTips: 'Ensure pupils receive credit for using scientific vocabulary correctly (evaporation, condensation, precipitation, molecules, transpiration). Accept contextual everyday examples.',
};
